# Generated by Django 4.1.2 on 2022-10-31 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_varation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Varation',
            new_name='Variation',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='varation_category',
            new_name='variation_category',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='varation_value',
            new_name='variation_value',
        ),
    ]